We have next logging message: 2023-02-19 11:24:36,404:ERROR-Exception
Traceback (most recent call last):
  File "D:\pythonProject1\les8.py", line 8, in <module>
    print(10/0)
ZeroDivisionError: division by zero
We have next logging message: 2023-02-19 11:24:36,413:DEBUG-debug
We have next logging message: 2023-02-19 11:24:36,413:INFO-info
